### ISSUE TITLE
Where is 4.18.2 tag?

### ISSUE THREAD

**Issue by amereii** [adtrace/ios_sdk#1]
In https://github.com/adtrace/adtrace_sdk_iOS/tags we have only 1.0.0 tag

![image](https://user-images.githubusercontent.com/16239920/72341305-2388db80-36df-11ea-8982-836e5ff8ed09.png)

So how can I have 

```
pod 'Adtrace', :git => 'https://github.com/adtrace/ios_sdk.git', :tag => 'v4.18.2'
```

I want to fix https://github.com/adtrace/adtrace_sdk_react_native/issues/2 ,there is no AdTrace package in cocoapods,Why?

![image](https://user-images.githubusercontent.com/16239920/72341369-4adfa880-36df-11ea-878c-f457d6464afc.png)

**Comment by arefhosseini** [comment]
We have Adtrace in cocoapods now, check it with [this link](https://cocoapods.org/pods/adtrace). You can use `1.0.1` version.
Thanks for mention that.
