### ISSUE TITLE
currency conversion link

### ISSUE THREAD

**Issue by owdax** [adtrace/ios_sdk#2]
can't open following link:
https://docs.adtrace.io/en/event-tracking/#tracking-purchases-in-different-currencies

**Comment by namini40** [comment]
dear @omiddlk our website is currently under test and revision. it'll be available pretty soon. in your case the currencies you can use would be as follows:

|Currency| Sign |
|---|---| 
|IR Rial| "IRR" , "Rial", "IRI"|
|IR Toman| "TOMAN" , "toman" , "Tom" , "Tooman" , "Touman" |
| Euro (€) | "EUR"|
| USD ($) | "USD"|
