### ISSUE TITLE
how to forget device?

### ISSUE THREAD

**Issue by owdax** [adtrace/ios_sdk#3]
http://app.adtrace.io/forget_device?app_token={yourAppToken}&adid={adidValue}

this link is not working.

**Comment by arefhosseini** [comment]
This isn't developed yet.

**Comment by owdax** [comment]
so how to forget an iOS device and test SDK?

**Comment by namini40** [comment]
this feature is under development and soon will be available. so i'm closing the issue and let you know when it's done!
