### ISSUE TITLE
Compatibility with xcode 13 beta

### ISSUE THREAD

**Issue by alireza12t** [adtrace/ios_sdk#4]
I have an error in lines 247-250 of Adtrace.m

Implicit conversion of 'NSURLRequestAttribution' (aka 'enum NSURLRequestAttribution') to 'ADTAttribution * _Nullable' is disallowed with ARC
Multiple methods named 'attribution' found with mismatched result, parameter type or attributes

**Comment by Mor4eza** [comment]
I have the same error.
I updated the library to the latest version, the problem was not solved.

**Comment by namini40** [comment]
dear @Mor4eza @alireza12t 
thank for your attention. 
this problem is due to using our package with XCode 13 and you can use `beta` branch to solve it temporarily.
glad to inform you that the new update is on the way and will be available soon! (more features and more compatibility)

**Comment by sootood** [comment]
@namini40  
hi i have same problem in react native does it solve ?

**Comment by namini40** [comment]
@sootood 
thanks for your feedback! currently ios sdk has been updated. other packages that are depend on this package (e.g. flutter sdk, react native sdk) are on the way to be updated soon. you can manually fix this manually in your react native project or just wait a little for the updates.
