### ISSUE TITLE
Xcode 13 build issue

### ISSUE THREAD

**Issue by owdax** [adtrace/ios_sdk#6]
hi @arefhosseini 

can't build the latest release `1.1.0` , and got this error:

```
Implicit conversion of 'NSURLRequestAttribution' (aka 'enum NSURLRequestAttribution') to 'ADTAttribution * _Nullable' is disallowed with ARC
``` 
for this method in Adtrace.m file
```
+ (ADTAttribution *)attribution {
    @synchronized (self) {
        return [[Adtrace getInstance] attribution];
    }
}
```

Xcode 13.2
M1 processor

**Comment by owdax** [comment]
@arefhosseini  @einali  @namini40  @hastiranjkesh @adtraceadmin

**Comment by namini40** [comment]
dear @omiddlk 
use `pod 'Adtrace', :git => 'https://github.com/adtrace/ios_sdk.git', :tag => '1.1.0'` instead. pods repo still under review and will be updated soon!
thanks for the feedback
