### ISSUE TITLE
Error in xcode 13.2

### ISSUE THREAD

**Issue by J-Arji** [adtrace/ios_sdk#7]
I got this error when I added adtrace.
```
Implicit conversion of 'NSURLRequestAttribution' (aka 'enum NSURLRequestAttribution') to 'ADTAttribution * _Nullable' is disallowed with ARC
Multiple methods named 'attribution' found with mismatched result, parameter type or attributes
```
<img width="1111" alt="Screen Shot 2022-03-14 at 21 56 27" src="https://user-images.githubusercontent.com/11584951/158237896-a9122ac4-04e2-4548-8b23-d42605d547e5.png">

how can fix this issue?

**Comment by namini40** [comment]
@J-Arji now you can use adtrace without any problem.
you can also use `beta` branch.
